"""Builds the v8 portrait asset: one small PNG the browser samples at runtime.

Channels:  R = luminance   G = sqrt-encoded sampling weight   B = soft silhouette mask
Run:       .venv/bin/python tools/build-portrait.py
"""
import json, os
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'img-6.jpg')
OUT_PNG = os.path.join(HERE, '..', 'assets', 'portrait.png')
OUT_META = os.path.join(HERE, '..', 'js', 'portrait-meta.js')

SUBJECT_POLY = [
    (0.335,0.070),(0.445,0.050),(0.565,0.068),(0.605,0.130),
    (0.590,0.220),(0.605,0.300),(0.640,0.345),(0.720,0.385),
    (0.790,0.440),(0.820,0.520),(0.800,0.600),
    (0.550,0.630),(0.380,0.600),(0.336,0.552),
    (0.330,0.470),(0.334,0.435),(0.470,0.432),(0.430,0.402),
    (0.400,0.394),(0.372,0.358),(0.352,0.312),(0.340,0.268),
    (0.333,0.222),(0.330,0.172),(0.333,0.126),
]
EYE = (0.463, 0.249)
EYE_OTHER = (0.392, 0.270)
FACE_CENTER = (0.455, 0.262)
WK = 900

img = Image.open(SRC).convert('RGB')
H6 = round(img.size[1] * WK / img.size[0])
small = img.resize((WK, H6), Image.LANCZOS)
L = np.asarray(small.convert('L'), dtype=np.float32) / 255.0
blur = np.asarray(small.convert('L').filter(ImageFilter.GaussianBlur(1.5)), dtype=np.float32) / 255.0
gy, gx = np.gradient(blur)
edge = np.sqrt(gx * gx + gy * gy)
edge = np.clip(edge / (np.percentile(edge, 99) + 1e-6), 0, 1)

mi = Image.new('L', (WK, H6), 0)
ImageDraw.Draw(mi).polygon([(x * WK, y * H6) for x, y in SUBJECT_POLY], fill=255)
mask = np.asarray(mi.filter(ImageFilter.GaussianBlur(2)), dtype=np.float32) / 255.0
soft = np.asarray(mi.filter(ImageFilter.GaussianBlur(9)), dtype=np.float32) / 255.0

yy, xx = np.mgrid[0:H6, 0:WK]
xf, yf = xx / WK, yy / H6
fgauss = np.exp(-(((xf - FACE_CENTER[0]) ** 2) / (2 * 0.105 ** 2) + ((yf - FACE_CENTER[1]) ** 2) / (2 * 0.135 ** 2)))
bfade = np.clip(1.0 - (yf - 0.44) * 2.2, 0.12, 1.0)
w = mask * (0.06 + 1.10 * (L ** 2.0) + 1.30 * edge) * (0.25 + 2.0 * fgauss) * bfade

rows = np.where(mask.max(axis=1) > 0.5)[0]
cols = np.where(mask.max(axis=0) > 0.5)[0]
pad = 12
x0, x1 = max(0, cols.min() - pad), min(WK, cols.max() + pad)
y0, y1 = max(0, rows.min() - pad), min(H6, rows.max() + pad)

wc = w[y0:y1, x0:x1]
wenc = np.sqrt(wc / wc.max())
rgb = np.stack([
    np.clip(L[y0:y1, x0:x1] * 255, 0, 255),
    np.clip(wenc * 255, 0, 255),
    np.clip(soft[y0:y1, x0:x1] * 255, 0, 255),
], axis=-1).round().astype(np.uint8)
os.makedirs(os.path.dirname(OUT_PNG), exist_ok=True)
Image.fromarray(rgb, 'RGB').save(OUT_PNG, optimize=True)

sc = 2.0 / float(rows.max() - rows.min())
cx, cy = FACE_CENTER[0] * WK - x0, FACE_CENTER[1] * H6 - y0
def to_local(p):
    return [round((p[0] * WK - x0 - cx) * sc, 4), round(-(p[1] * H6 - y0 - cy) * sc, 4)]

meta = {
    'width': int(x1 - x0), 'height': int(y1 - y0),
    'cx': round(cx, 3), 'cy': round(cy, 3), 'scale': round(sc, 6),
    'eye': to_local(EYE), 'eyeOther': to_local(EYE_OTHER),
    'bboxLocal': [round((0 - cx) * sc, 3), round(-((y1 - y0) - cy) * sc, 3),
                  round(((x1 - x0) - cx) * sc, 3), round(-(0 - cy) * sc, 3)],
}
with open(OUT_META, 'w') as f:
    f.write('// generated by tools/build-portrait.py\nexport const PORTRAIT = ' + json.dumps(meta) + ';\n')
print(json.dumps(meta), os.path.getsize(OUT_PNG), 'bytes')
