// generated by tools/build-portrait.py
export const PORTRAIT = {"width": 464, "height": 442, "cx": 124.5, "cy": 164.688, "scale": 0.004785, "eye": [0.0344, 0.045], "eyeOther": [-0.2713, -0.0277], "bboxLocal": [-0.596, -1.327, 1.624, 0.788]};
